---
apiVersion: "apps/v1"
kind: "StatefulSet"
spec:
  template:
    spec:
      containers:
        - env:
            - name: MAIL_USER
              valueFrom:
                configMapKeyRef:
                  name: simple-pw-config
                  key: mailuser