---
apiVersion: "apps/v1"
kind: "StatefulSet"
spec:
  template:
    spec:
      containers:
        - name: jenkins
          env:
             #ENV varibale name
            - name: MAIL_USER
              valueFrom:
                configMapKeyRef:
                  name: simple-pw-config
                  key: mailuser
            #ENV varibale name
            - name: MAIL_PW
              valueFrom:
                configMapKeyRef:
                  #name of the configmap
                  name: simple-pw-config
                  #name of the key inside the property file
                  key: mailpw
            #ENV varibale name
            - name: GITHUB_USER_SSH_TMP
              valueFrom:
                secretKeyRef:
                  #uniq key
                  key: GITHUB_USER_SSH_TMP
                  #name of the k8s secret
                  name: github-user-ssh-tmp


---
apiVersion: "apps/v1"
kind: "StatefulSet"
spec:
  template:
    spec:
      containers:
        - name: jenkins
          env:
            - name: MAIL_USER
              valueFrom:
                configMapKeyRef:
                  name: simple-pw-config
                  key: mailuser
            - name: MAIL_PW
              valueFrom:
                configMapKeyRef:
                  name: simple-pw-config
                  key: mailpw
            - name: GITHUB_USER_SSH_TMP
              valueFrom:
                secretKeyRef:
                  key: GITHUB_USER_SSH_TMP
                  name: github-user-ssh-tmp


---
apiVersion: "apps/v1"
kind: "StatefulSet"
spec:
  template:
    spec:
      containers:
        - name: jenkins
          volumeMounts:
            - mountPath: "/run/secrets/github-user-ssh-tmp"
              name: "github-user-ssh-tmp"
      volumes:
        - name: github-user-ssh-tmp
          secret:
            secretName: github-user-ssh-tmp

