---
apiVersion: "apps/v1"
kind: "StatefulSet"
spec:
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    spec:
      containers:
        - name: "jenkins"
          volumeMounts:
            - name: "backup"
              mountPath: "/backup"
            - name: controller-secrets
              mountPath: /var/run/secrets/controller
              readOnly: true
      volumes:
        - name: controller-secrets
          secret:
            defaultMode: 420
            secretName: controller-secrets