---
apiVersion: "apps/v1"
kind: "StatefulSet"
spec:
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "kubernetes.io/os"
                    operator: "In"
                    values:
                      - "linux"
                  - key: "cloudbees.custom.controller"
                    operator: "In"
                    values:
                      - "controller"
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "com.cloudbees.cje.type"
                      operator: "In"
                      values:
                        - "cjoc"
                topologyKey: "kubernetes.io/hostname"
              weight: 1
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "jenkins"
                      operator: "In"
                      values:
                        - "slave"
                topologyKey: "kubernetes.io/hostname"
              weight: 1
      containers:
        - name: "jenkins"
          volumeMounts:
            - name: "backup"
              mountPath: "/backup"
      volumes:
        - name: backup
          persistentVolumeClaim:
            claimName: backup-pvc
